### ISSUE TITLE
Android-access without Google-Account

### ISSUE THREAD

**Issue by feinstaub** [dbbahnhoflive/dbbahnhoflive-android#4]
First of all, congratuations and thank you for going the Open Source path with this app. New experiences will wait for you :-).

To the issue: Privacy-concerned citizens usually want to avoid having a Google-Account when using non-Google services. This is why F-Droid was build and is now heavily used by the community (see https://f-droid.org/de/2019/05/05/trust-privacy-and-free-software.html and https://secuso.aifb.kit.edu/105.php). How can the DB Bahnhof live App also be accessed there instead of only via Google Play Store?

**Comment by SuVpmoran** [comment]
Hi @feinstaub ,
Thank you very much for your warm words and of course for the relevant reference towards the F-Droid repository. We already decided to transfer your request to our backlog to evaluate this step, though we cannot promise a positive outcome.

One last word: Due to holiday season and Corona we kindly ask for your understanding in regards of timing and prioritization.

**Comment by IzzySoft** [comment]
@feinstaub thanks for raising the issue!

@SuVpmoran I see the app on Playstore uses Firebase, which will be a, well, problem when going for F-Droid (being proprietary, Firebase is not permitted there – F-Droid needs to build *everything* from source, which is only possible if all components are open-source). So as a pointer: you could establish a build flavor coming without Firebase/Crashlytics, which then would be acceptable.

<sup>(Disclosure: I'm one of the F-Droid maintainers)</sup>

**Comment by feinstaub** [comment]
As intermediate step, I would also be glad if the app was available in F-Droid via a 3rd party repository (where the app provider has full control over the rules).

**Comment by IzzySoft** [comment]
@SuVpmoran maybe you could attach the signed APK to your releases here? That would at least make it available without access to Play Store – and I could see if I can add it to [my repo](https://apt.izzysoft.de/fdroid) then, which would satisfy the "intermediate step" suggested by @feinstaub.

**Comment by SuVpmoran** [comment]
Hi @IzzySoft, & @feinstaub, 

thanks again for raising this issue, we evaluated the option of being present on F-Droid and see the need and potential of it. At the moment though we do not feel that we are at the point yet to take this to action. 

The main reason for our decision is that we do not have a state of the FOSS DB Bahnhof live app yet, which has a scope of functionality, that might be satisfying. Additionally to that some parts of the code would need to be restructured.  

Right now we are still in the beginning of our journey to go „full" Open Source. We try our best in the meantime to offer a first increment of what that might look like here on GitHub. 

Nonetheless you pointed out with this request, the major things we still need to get solved, like: 
. Offering access to a wider range of APIs for the community
. Offering UI assets of the look and feel of the official application
. Providing an application that is free and open source with every component used in it. 

All these points rapidly raise the quality of this project in general. We will profit from the synergy of simultaneously having an app that is ready to be published on F-Droid and having a more useful application on GitHub. So please be patient, because as we reached an higher maturity in this project this topic will become relevant in our [ROADMAP](https://github.com/dbbahnhoflive/dbbahnhoflive-android/blob/master/ROADMAP.md).

Hope to hear from you soon!

**Comment by IzzySoft** [comment]
Thanks for your feedback and for working on it, @SuVpmoran! My offer still stands: if on your road to "going full FOSS" you reach a point where your app would meet the inclusion criteria of my repo (but not yet F-Droid's), remember you can use my repo as a "stepping stone" – hundreds of apps have done so before. Results of my library scanner could e.g. help you finding out when a "clean point" might have been reached and you're ready to apply for listing at F-Droid.org (provided there are no pre-built JARs/AARs which my updater does not check for). Being available in my repo would also make it easier for potential testers to stay up-to-date without too much hazzle.

Whichever path you choose: wishing all the best and good progress!
